[GOOGLE_SHEETS_CREDS]
type = "service_account"
project_id = "optical-legend-463817-f9"
private_key_id = "0a4726652dcb3d51b40ea1bbfb636b822bdb1e39"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDgWxKk+fr6Qoub
xcRKgFvo3Vkw2A+/OZ/addbak2QwU6/TCryrYPbQOGEZZ5kxp9tZIILqAy0R4DM1
sA/9J/IBo7gsiXC+oTvCuo7cfCMZu2ItK7YdfA+Khei25GL/drfQs/h7xaf8pYQQ
kfv/kkPY3s7Bv7p8fMvbirdzdgYb0vr0N2hcbUsRBuAi19+7wp/SAwYQKoMXk4bw
+KQksnNImG7WQ/BFueEFgM/SHBp7Yh11UL/I/PmVnVx0Gk9UroainO2rTDXQLMW2
DqqUpYBpFRhdbaKLwRh6OR2Mq+9kxGeRMKm5kazdt669+9lElZxCpaw1n97PpE9R
JNT0OaKnAgMBAAECggEAArwUHpmuHaXOViroyRsGbnC1mRr7xNIa04qzKz03r+py
jrPR9+l501uUkhQ0Bv8WSor9vYTQuafjcpM/pqTO1jFHhJd08zCQ7hSLED9HyD+t
+IH7ZCGdKOGX+WllltqSGVj66DtRCwsoxcZEbZQ7/8/mHPDNgPNJItcZLwRFxR9d
ODZ0yPkGUQHwW382wrhz5UsrvQx9gjXt1MhSoK6XYaZQNUXFfVMPbjrn6CJRms+R
Atn1hVTuRF9eZe3DUZdeGReuY77ZOsiyH6eUHijkMVF6eJZLN8xmSVDSo+q6GECN
rp6joQDRnLhl7VM5+JqAyFZHTEi8uia9NnXlxWv8SQKBgQDzYBnS0hSBJEwLJJaD
lFRjXCsCBpi8iWp+ZbSAN8MsGWfk/WjJwO8EUOeR9ghDCg4ltfdU0Ivh9lOFkg6H
1Sk9sZpMqiZLUB/11A98orrZmNWaHigqzQaqOLLZTsuQapvl19pznz55uLYe7+g1
vjgkYy+M0LcFApaCpJ6iSWPMqQKBgQDr/mamwvhlSaMNyjW9mNxwkGvZBjzwr4/x
gmdrp8AYeqaRxyFNXxFxhdzeqwbyRFqzg6UkezU9cm7R7V731B4j/mFi23hkEzjM
kNqPE7kUc/O3e6XiUwN4Vckmyejpvwm1ozp286wKAWCj0OlnAtJQqrmXVfFyRbh9
72nDJi+2zwKBgH3KEO7PGDv7V7Z2rbjKZKeKTsxYPn9MAxfbV2Th7WWQqAtKEuwc
ZS1054ugf3qu6ssA9xoGRBaBa3/hEtOQECXL8vVnCC3q9unnNi30KeEnxldG+PnO
SICYl5AL0tkM0REF9OnHx9G/75mj5ABLFddw0HXWtpHHWaWikj9M8WEpAoGBAMiq
Q0LdWjVWDe112Yhj6F1WkD2zjjHiNnVXOvVRaIfoEqa2Odz+T2jGOG6l4nwyHyWx
dMS2dyjOmuip/CyjExXsAYb7szz1E0DukslCLgf0KHIGE6GEkNjLqQTwfrnzFSB7
sQTgYZMIZNImm7BZt9ebs7+49lsCacO7xaSIXd4FAoGABVILjFpEbsC6tGyrZNRi
mwE3Qhq/owWSlMuvhD+dhQmNvHx4wM0eicpXKfokztDfdWlwK5yOGrNkqJvy7LeC
8NZA/ExUDikkYRHQbzIVBwD3H7ILd5ZmAC1MgcAqwQewpni0qGNysPMFagwtgJ0R
VHtY4JeVEnObjZg67DTgzvI=
-----END PRIVATE KEY-----"""
client_email = "streamlit-expense-bot@optical-legend-463817-f9.iam.gserviceaccount.com"
client_id = "107997957691340311027"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-expense-bot%40optical-legend-463817-f9.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
